Temporarily remove obsidian package
It is currently relying on an EOL version of Electron, which throws an error
message when trying to work on anything else within the repo:

    error: Package ‘electron-13.6.9’ in /nix/store/09nmz4s952xg31z18qqc47vp7lanvdk3-source/pkgs/development/tools/electron/generic.nix:26 is marked as insecure, refusing to evaluate.

Luckily, a fix has already been merged in nixpkgs, but it's not yet available to
pull yet, so this should only be necessary for a couple of days.

See:
- https://github.com/NixOS/nixpkgs/issues/158956